# Generated by Django 4.2.10 on 2026-03-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Elite Laptops', 'Elite Laptops'), ('Mechanical Keyboards', 'Mechanical Keyboards'), ('Pro Peripherals', 'Pro Peripherals'), ('Workstation Setup', 'Workstation Setup')], default='Elite Laptops', max_length=50),
        ),
    ]
