# Generated by Django 5.2.7 on 2025-12-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_book_artist_cls_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback_cls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('feedback', models.CharField()),
            ],
        ),
    ]
