# Generated by Django 5.2.7 on 2025-12-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_user_register_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_artist_cls',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
