# Generated by Django 5.2.7 on 2025-11-29 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_mynotes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
