# Generated by Django 5.2.7 on 2025-11-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='city',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='number',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
