# Generated by Django 5.2.7 on 2025-11-30 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_userdata_city_userdata_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='number',
            new_name='mobil',
        ),
    ]
