# Generated by Django 5.2.7 on 2025-12-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_contact_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='profile_img',
            field=models.ImageField(default='default.png', upload_to='profile_images/'),
        ),
    ]
