# Generated by Django 5.2.7 on 2025-12-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_product_category_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Gaming Laptop', 'Gaming Laptop'), ('Ultrabook', 'Ultrabook'), ('MacBook', 'MacBook'), ('Business Laptop', 'Business Laptop'), ('Student Laptop', 'Student Laptop'), ('Workstation Laptop', 'Workstation Laptop'), ('2-in-1 Laptop', '2-in-1 Laptop'), ('Convertible Laptop', 'Convertible Laptop'), ('Budget Laptop', 'Budget Laptop'), ('Premium Laptop', 'Premium Laptop'), ('Chromebook', 'Chromebook'), ('Creator Laptop', 'Creator Laptop'), ('AI Laptop', 'AI Laptop'), ('Touchscreen Laptop', 'Touchscreen Laptop'), ('Thin & Light Laptop', 'Thin & Light Laptop'), ('Rugged Laptop', 'Rugged Laptop')], max_length=50),
        ),
    ]
