# Generated by Django 5.2.7 on 2025-11-20 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogin',
            old_name='confirmpassword',
            new_name='confirm_password',
        ),
    ]
