# Generated by Django 5.2.7 on 2025-12-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_artist',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
