# Generated by Django 5.2.7 on 2025-12-08 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_file_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback_artist_cls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.register_artist')),
            ],
        ),
    ]
