# Generated by Django 5.2.7 on 2025-12-09 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_feedback_artist_cls'),
        ('customer', '0005_feedback_cls_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='artist_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.register_artist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.user_register')),
            ],
        ),
    ]
