# Generated by Django 5.2.7 on 2025-12-09 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_artist_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='artist_booking',
        ),
    ]
