# Generated by Django 5.2.7 on 2025-12-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0006_delete_artist_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_artist',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
