# Generated by Django 5.2.7 on 2025-12-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_register',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
