# Generated by Django 5.2.7 on 2025-12-20 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_contact_cls'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_cls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('mm_yy', models.CharField(blank=True, max_length=5, null=True)),
                ('cvv', models.CharField(blank=True, max_length=4, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('cash_on_delivery', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_register')),
            ],
        ),
    ]
