# Generated by Django 5.2.7 on 2025-12-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_payment_cls'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_cls',
            name='total_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
