# Generated by Django 5.2.7 on 2025-12-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_cls',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
