# Generated by Django 5.2.7 on 2025-12-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_artist_cls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistname', models.CharField(verbose_name=50)),
                ('date', models.DateField()),
                ('location', models.CharField(verbose_name=100)),
            ],
        ),
    ]
