# Generated by Django 5.2.7 on 2025-12-07 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_book_artist_cls'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_artist_cls',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.user_register'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book_artist_cls',
            name='artistname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book_artist_cls',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
