# Generated by Django 5.2.7 on 2025-12-07 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_feedback_cls'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_cls',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.user_register'),
            preserve_default=False,
        ),
    ]
