# Generated by Django 5.2.7 on 2025-12-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_feedback_cls_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_register',
            name='mobile',
            field=models.CharField(max_length=100),
        ),
    ]
