# Generated by Django 5.2.7 on 2025-12-08 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_alter_register_artist_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.register_artist')),
            ],
        ),
    ]
