# Generated by Django 5.2.7 on 2025-12-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0007_register_artist_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_artist',
            name='approved',
        ),
        migrations.AddField(
            model_name='register_artist',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve'), ('Reject', 'Reject')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
