# Generated by Django 4.2 on 2025-11-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_usersignup_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersignup',
            name='username',
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='password',
            field=models.CharField(max_length=15),
        ),
    ]
